from pathlib import Path
import pandas as pd


def write_markdown_report(
    summary: pd.DataFrame,
    output_path: str,
    title: str = "RDE Validation Report",
) -> None:
    output_path = Path(output_path)

    lines = []

    lines.append(f"# {title}")
    lines.append("")
    lines.append("This report was generated by the reusable RDE Validation Framework.")
    lines.append("")
    lines.append("## Validation Dataset Summary")
    lines.append("")

    if summary.empty:
        lines.append("No validation results available.")
    else:
        lines.append(summary.to_markdown(index=False))

    lines.append("")
    lines.append("## Interpretation Notes")
    lines.append("")
    lines.append(
        "This report summarizes external or internal validation datasets "
        "registered with the validation engine. Strong validation should come "
        "from datasets that are independent of the model construction process."
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")
